### ISSUE TITLE
メッセージ機能実装

### ISSUE THREAD

**Issue by NakasaiHayato** [HAL-Tokyo/nicopachi#34]
モデル追加してLINEみたいなトークルームを作成

**Comment by ttrweb** [comment]
先にモデル追加のIssueやったりフォロー（キニナル）機能もつけて体から、これ一旦stayじゃないkな

**Comment by ttrweb** [comment]
粒度細かく切った方が管理しやすいかも

**Comment by ttrweb** [comment]
Clientモデル作成 / フォロー機能実装 / チャット機能実装　でissueそれぞれ分けちゃいましょう
