### ISSUE TITLE
江藤MUST指示　朝トイレに行ったらうんこを食べろ

### ISSUE THREAD

**Issue by Etotomohiro** [HAL-Tokyo/nicopachi#50]
水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな水に流すな尻拭くな

**Comment by Etotomohiro** [comment]
すいません。荒らした。

**Comment by Masashige-T** [comment]
了解です
